apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-jwt-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-jwt-api
  template:
    metadata:
      labels:
        app: simple-jwt-api
    spec:
      containers:
        - name: simple-jwt-api
          image: vuxhiep97/simple-jwt-api
          ports:
            - containerPort: 8080
          env:
            - name: JWT_SECRET
              value: "abc123abc1234"
